// Code generated by gimpl. DO NOT EDIT.
package example

import (
	"strings"
)

func (e Address) SortPtr(field string) any {
	switch field {
	case "street":
		return &e.Street
	default:
		if strings.HasPrefix(field, "country_") {
			return e.Country.SortPtr(strings.TrimPrefix(field, "country_"))
		}
	}
	return nil
}

func (e Address) FilterPtr(field string) any {
	switch field {
	default:
		if strings.HasPrefix(field, "country_") {
			return e.Country.FilterPtr(strings.TrimPrefix(field, "country_"))
		}
	}
	return nil
}

func (e Address) PgColumn(field string) string {
	switch field {
	case "street":
		return "street"
	case "city":
		return "city"
	case "zip":
		return "zip"
	default:
		if strings.HasPrefix(field, "country_") {
			return "country_" + e.Country.PgColumn(strings.TrimPrefix(field, "country_"))
		}
	}
	return ""
}

func (e Address) PgColumns() []string {
	cols := []string{
		"street",
		"city",
		"zip",
	}
	for _, c := range e.Country.PgColumns() {
		cols = append(cols, "country_"+c)
	}
	return cols
}

func (e Address) NewWithPgColumnPtrs() (any, []any) {
	n := &Address{}
	ptrs := []any{
		&n.Street,
		&n.City,
		&n.Zip,
	}
	{
		inner, innerPtrs := n.Country.NewWithPgColumnPtrs()
		if val, ok := inner.(*Country); ok {
			n.Country = *val
		}
		ptrs = append(ptrs, innerPtrs...)
	}
	return n, ptrs
}

func (e Address) CreatePgColumns() []string {
	cols := []string{
		"street",
		"city",
		"zip",
	}
	for _, c := range e.Country.CreatePgColumns() {
		cols = append(cols, "country_"+c)
	}
	return cols
}

func (e Address) CreatePgColumnVals() []any {
	vals := []any{
		e.Street,
		e.City,
		e.Zip,
	}
	vals = append(vals, e.Country.CreatePgColumnVals()...)
	return vals
}

func (e Address) IdentifyPgColumns() []string {
	cols := []string{}
	for _, c := range e.Country.IdentifyPgColumns() {
		cols = append(cols, "country_"+c)
	}
	return cols
}

func (e Address) IdentifyPgColumnVals() []any {
	vals := []any{}
	vals = append(vals, e.Country.IdentifyPgColumnVals()...)
	return vals
}

func (e Address) UpdatePgColumns() []string {
	cols := []string{
		"street",
		"city",
		"zip",
	}
	for _, c := range e.Country.UpdatePgColumns() {
		cols = append(cols, "country_"+c)
	}
	return cols
}

func (e Address) UpdatePgColumnVals() []any {
	vals := []any{
		e.Street,
		e.City,
		e.Zip,
	}
	vals = append(vals, e.Country.UpdatePgColumnVals()...)
	return vals
}

func (e Country) SortPtr(field string) any {
	switch field {
	case "code":
		return &e.Code
	}
	return nil
}

func (e Country) FilterPtr(field string) any {
	switch field {
	}
	return nil
}

func (e Country) PgColumn(field string) string {
	switch field {
	case "code":
		return "code"
	case "name":
		return "name"
	}
	return ""
}

func (e Country) PgColumns() []string {
	cols := []string{
		"code",
		"name",
	}
	return cols
}

func (e Country) NewWithPgColumnPtrs() (any, []any) {
	n := &Country{}
	ptrs := []any{
		&n.Code,
		&n.Name,
	}
	return n, ptrs
}

func (e Country) CreatePgColumns() []string {
	cols := []string{
		"code",
		"name",
	}
	return cols
}

func (e Country) CreatePgColumnVals() []any {
	vals := []any{
		e.Code,
		e.Name,
	}
	return vals
}

func (e Country) IdentifyPgColumns() []string {
	cols := []string{}
	return cols
}

func (e Country) IdentifyPgColumnVals() []any {
	vals := []any{}
	return vals
}

func (e Country) UpdatePgColumns() []string {
	cols := []string{
		"code",
		"name",
	}
	return cols
}

func (e Country) UpdatePgColumnVals() []any {
	vals := []any{
		e.Code,
		e.Name,
	}
	return vals
}

func (e User) SortPtr(field string) any {
	switch field {
	case "id":
		return &e.ID
	case "name":
		return &e.Name
	default:
		if strings.HasPrefix(field, "address_") {
			return e.Address.SortPtr(strings.TrimPrefix(field, "address_"))
		}
	}
	return nil
}

func (e User) FilterPtr(field string) any {
	switch field {
	case "id":
		return &e.ID
	case "name":
		return &e.Name
	default:
		if strings.HasPrefix(field, "address_") {
			return e.Address.FilterPtr(strings.TrimPrefix(field, "address_"))
		}
	}
	return nil
}

func (e User) PgColumn(field string) string {
	switch field {
	case "id":
		return "id"
	case "name":
		return "name"
	default:
		if strings.HasPrefix(field, "address_") {
			return "address_" + e.Address.PgColumn(strings.TrimPrefix(field, "address_"))
		}
	}
	return ""
}

func (e User) PgColumns() []string {
	cols := []string{
		"id",
		"name",
	}
	for _, c := range e.Address.PgColumns() {
		cols = append(cols, "address_"+c)
	}
	return cols
}

func (e User) NewWithPgColumnPtrs() (any, []any) {
	n := &User{}
	ptrs := []any{
		&n.ID,
		&n.Name,
	}
	{
		inner, innerPtrs := n.Address.NewWithPgColumnPtrs()
		if val, ok := inner.(*Address); ok {
			n.Address = *val
		}
		ptrs = append(ptrs, innerPtrs...)
	}
	return n, ptrs
}

func (e User) CreatePgColumns() []string {
	cols := []string{}
	for _, c := range e.Address.CreatePgColumns() {
		cols = append(cols, "address_"+c)
	}
	return cols
}

func (e User) CreatePgColumnVals() []any {
	vals := []any{}
	vals = append(vals, e.Address.CreatePgColumnVals()...)
	return vals
}

func (e User) IdentifyPgColumns() []string {
	cols := []string{
		"id",
	}
	for _, c := range e.Address.IdentifyPgColumns() {
		cols = append(cols, "address_"+c)
	}
	return cols
}

func (e User) IdentifyPgColumnVals() []any {
	vals := []any{
		e.ID,
	}
	vals = append(vals, e.Address.IdentifyPgColumnVals()...)
	return vals
}

func (e User) UpdatePgColumns() []string {
	cols := []string{}
	for _, c := range e.Address.UpdatePgColumns() {
		cols = append(cols, "address_"+c)
	}
	return cols
}

func (e User) UpdatePgColumnVals() []any {
	vals := []any{}
	vals = append(vals, e.Address.UpdatePgColumnVals()...)
	return vals
}
