version: "3"

tasks:
  default:
    cmds:
      - task --list

  deps:
    desc: Install dependencies
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go mod download

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run

  test:
    desc: Run tests
    cmds:
      - go test ./...

  build:
    desc: Build the CLI tool
    cmds:
      - go build -o build/gimpl ./cmd/gimpl/*.go
    sources:
      - Taskfile.yml
      - "**/*.go"
    generates:
      - build/gimpl

  gimpl:
    desc: Run the gimpl CLI tool
    deps:
      - build
    cmds:
      - build/gimpl {{.CLI_ARGS}}
