// Code generated by gimpl. DO NOT EDIT.
package shared

func (e Geo) SortPtr(field string) any {
	switch field {
	}
	return nil
}

func (e Geo) FilterPtr(field string) any {
	switch field {
	}
	return nil
}

func (e Geo) PgColumn(field string) string {
	switch field {
	case "lat":
		return "pg_lat"
	case "lon":
		return "pg_lon"
	}
	return ""
}

func (e Geo) PgColumns() []string {
	cols := []string{
		"pg_lat",
		"pg_lon",
	}
	return cols
}

func (e Geo) NewWithPgColumnPtrs() (any, []any) {
	n := &Geo{}
	ptrs := []any{
		&n.Lat,
		&n.Lon,
	}
	return n, ptrs
}

func (e Geo) CreatePgColumns() []string {
	cols := []string{
		"pg_lat",
		"pg_lon",
	}
	return cols
}

func (e Geo) CreatePgColumnVals() []any {
	vals := []any{
		e.Lat,
		e.Lon,
	}
	return vals
}

func (e Geo) IdentifyPgColumns() []string {
	cols := []string{}
	return cols
}

func (e Geo) IdentifyPgColumnVals() []any {
	vals := []any{}
	return vals
}

func (e Geo) UpdatePgColumns() []string {
	cols := []string{
		"pg_lat",
		"pg_lon",
	}
	return cols
}

func (e Geo) UpdatePgColumnVals() []any {
	vals := []any{
		e.Lat,
		e.Lon,
	}
	return vals
}
