// Code generated by gimpl. DO NOT EDIT.
package users

import (
	shared "github.com/pedramktb/go-gimpl/example/shared"
	"strings"
)

func (e User) SortPtr(field string) any {
	switch field {
	default:
		if strings.HasPrefix(field, "") {
			return e.Location.SortPtr(strings.TrimPrefix(field, ""))
		}
	}
	return nil
}

func (e User) FilterPtr(field string) any {
	switch field {
	default:
		if strings.HasPrefix(field, "") {
			return e.Location.FilterPtr(strings.TrimPrefix(field, ""))
		}
	}
	return nil
}

func (e User) PgColumn(field string) string {
	switch field {
	case "id":
		return "id"
	default:
		if strings.HasPrefix(field, "") {
			return "" + e.Location.PgColumn(strings.TrimPrefix(field, ""))
		}
	}
	return ""
}

func (e User) PgColumns() []string {
	cols := []string{
		"id",
	}
	for _, c := range e.Location.PgColumns() {
		cols = append(cols, ""+c)
	}
	return cols
}

func (e User) NewWithPgColumnPtrs() (any, []any) {
	n := &User{}
	ptrs := []any{
		&n.ID,
	}
	{
		inner, innerPtrs := n.Location.NewWithPgColumnPtrs()
		if val, ok := inner.(*shared.Geo); ok {
			n.Location = *val
		}
		ptrs = append(ptrs, innerPtrs...)
	}
	return n, ptrs
}

func (e User) CreatePgColumns() []string {
	cols := []string{}
	for _, c := range e.Location.CreatePgColumns() {
		cols = append(cols, ""+c)
	}
	return cols
}

func (e User) CreatePgColumnVals() []any {
	vals := []any{}
	vals = append(vals, e.Location.CreatePgColumnVals()...)
	return vals
}

func (e User) IdentifyPgColumns() []string {
	cols := []string{
		"id",
	}
	for _, c := range e.Location.IdentifyPgColumns() {
		cols = append(cols, ""+c)
	}
	return cols
}

func (e User) IdentifyPgColumnVals() []any {
	vals := []any{
		e.ID,
	}
	vals = append(vals, e.Location.IdentifyPgColumnVals()...)
	return vals
}

func (e User) UpdatePgColumns() []string {
	cols := []string{}
	for _, c := range e.Location.UpdatePgColumns() {
		cols = append(cols, ""+c)
	}
	return cols
}

func (e User) UpdatePgColumnVals() []any {
	vals := []any{}
	vals = append(vals, e.Location.UpdatePgColumnVals()...)
	return vals
}
