package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"strings"
)

func generateFile(originalFile, pkgName string, structs []structInfo) error {
	g := &generator{
		buf:     &bytes.Buffer{},
		pkgName: pkgName,
		structs: structs,
	}
	return g.generate(originalFile)
}

type generator struct {
	buf     *bytes.Buffer
	pkgName string
	structs []structInfo
}

func (g *generator) generate(originalFile string) error {
	g.printf("// Code generated by gimpl. DO NOT EDIT.\n")
	g.printf("package %s\n\n", g.pkgName)

	g.generateImports()

	for _, s := range g.structs {
		g.generateCommonMethods(s)

		// Generate for specific targets
		for target := range s.Impls {
			switch target {
			case "pgimpl":
				g.generatePgMethods(s)
			}
		}
	}

	formatted, err := format.Source(g.buf.Bytes())
	if err != nil {
		return fmt.Errorf("failed to format generated code: %w", err)
	}

	outFile := strings.TrimSuffix(originalFile, ".go") + "_gen.go"
	return os.WriteFile(outFile, formatted, 0644)
}

func (g *generator) printf(format string, args ...interface{}) {
	fmt.Fprintf(g.buf, format, args...)
}

func (g *generator) generateImports() {
	hasDelegate := false
	imports := make(map[string]string) // alias -> path

	for _, s := range g.structs {
		for _, f := range s.Fields {
			if f.IsDelegate {
				hasDelegate = true
				if f.DelegateImportPath != "" {
					parts := strings.Split(f.TypeName, ".")
					if len(parts) > 1 {
						imports[parts[0]] = f.DelegateImportPath
					}
				}
			}
		}
	}

	if hasDelegate {
		g.printf("import (\n")
		g.printf("\t\"strings\"\n")
		for alias, path := range imports {
			g.printf("\t%s \"%s\"\n", alias, path)
		}
		g.printf(")\n\n")
	}
}

func (g *generator) generateCommonMethods(s structInfo) {
	// Check if any impl requires Entity
	var isEntity bool
	for _, set := range s.Impls {
		if set.IsEntity {
			isEntity = true
			break
		}
	}

	if isEntity {
		g.generateSortPtr(s)
		g.generateFilterPtr(s)
	}
}

func (g *generator) generateSortPtr(s structInfo) {
	g.printf("func (e %s) SortPtr(field string) any {\n", s.Name)
	g.printf("\tswitch field {\n")
	for _, f := range s.Fields {
		if f.IsDelegate {
			g.printf("\tdefault:\n")
			g.printf("\t\tif strings.HasPrefix(field, \"%s\") {\n", f.Prefix)
			g.printf("\t\t\treturn e.%s.SortPtr(strings.TrimPrefix(field, \"%s\"))\n", f.Name, f.Prefix)
			g.printf("\t\t}\n")
			continue
		}

		if f.Sort {
			g.printf("\tcase \"%s\":\n", f.FieldName)
			g.printf("\t\treturn &e.%s\n", f.Name)
		}
	}
	g.printf("\t}\n\treturn nil\n}\n\n")
}

func (g *generator) generateFilterPtr(s structInfo) {
	g.printf("func (e %s) FilterPtr(field string) any {\n", s.Name)
	g.printf("\tswitch field {\n")
	for _, f := range s.Fields {
		if f.IsDelegate {
			g.printf("\tdefault:\n")
			g.printf("\t\tif strings.HasPrefix(field, \"%s\") {\n", f.Prefix)
			g.printf("\t\t\treturn e.%s.FilterPtr(strings.TrimPrefix(field, \"%s\"))\n", f.Name, f.Prefix)
			g.printf("\t\t}\n")
			continue
		}
		if f.Filter {
			g.printf("\tcase \"%s\":\n", f.FieldName)
			g.printf("\t\treturn &e.%s\n", f.Name)
		}
	}
	g.printf("\t}\n\treturn nil\n}\n\n")
}

func (g *generator) generatePgMethods(s structInfo) {
	set := s.Impls["pgimpl"]

	if set.IsEntity {
		g.generatePgColumn(s)
		g.generatePgColumns(s)
		g.generateNewWithPgColumnPtrs(s)
	}

	if set.IsCreate {
		g.generateCreatePgColumns(s)
		g.generateCreatePgColumnVals(s)
	}

	if set.IsUpdate {
		g.generateIdentifyPgColumns(s)
		g.generateIdentifyPgColumnVals(s)
		g.generateUpdatePgColumns(s)
		g.generateUpdatePgColumnVals(s)
	}
}

func (g *generator) generatePgColumn(s structInfo) {
	g.printf("func (e %s) PgColumn(field string) string {\n", s.Name)
	g.printf("\tswitch field {\n")
	for _, f := range s.Fields {
		if f.IsDelegate {
			g.printf("\tdefault:\n")
			g.printf("\t\tif strings.HasPrefix(field, \"%s\") {\n", f.Prefix)
			g.printf("\t\t\treturn \"%s\" + e.%s.PgColumn(strings.TrimPrefix(field, \"%s\"))\n", f.Prefix, f.Name, f.Prefix)
			g.printf("\t\t}\n")
			continue
		}

		pgInfo := f.Impls["pgimpl"]
		g.printf("\tcase \"%s\":\n", f.FieldName)
		g.printf("\t\treturn \"%s\"\n", pgInfo.ColumnName)
	}
	g.printf("\t}\n\treturn \"\"\n}\n\n")
}

func (g *generator) generatePgColumns(s structInfo) {
	g.printf("func (e %s) PgColumns() []string {\n", s.Name)
	g.printf("\tcols := []string{\n")
	for _, f := range s.Fields {
		if f.IsDelegate {
			continue
		}
		pgInfo := f.Impls["pgimpl"]
		g.printf("\t\t\"%s\",\n", pgInfo.ColumnName)
	}
	g.printf("\t}\n")

	for _, f := range s.Fields {
		if f.IsDelegate {
			g.printf("\tfor _, c := range e.%s.PgColumns() {\n", f.Name)
			g.printf("\t\tcols = append(cols, \"%s\" + c)\n", f.Prefix)
			g.printf("\t}\n")
		}
	}
	g.printf("\treturn cols\n}\n\n")
}

func (g *generator) generateNewWithPgColumnPtrs(s structInfo) {
	g.printf("func (e %s) NewWithPgColumnPtrs() (any, []any) {\n", s.Name)
	g.printf("\tn := &%s{}\n", s.Name)
	g.printf("\tptrs := []any{\n")
	for _, f := range s.Fields {
		if f.IsDelegate {
			continue
		}
		g.printf("\t\t&n.%s,\n", f.Name)
	}
	g.printf("\t}\n")

	for _, f := range s.Fields {
		if f.IsDelegate {
			g.printf("\t{\n")
			g.printf("\t\tinner, innerPtrs := n.%s.NewWithPgColumnPtrs()\n", f.Name)
			g.printf("\t\tif val, ok := inner.(*%s); ok {\n", f.TypeName)
			g.printf("\t\t\tn.%s = *val\n", f.Name)
			g.printf("\t\t}\n")
			g.printf("\t\tptrs = append(ptrs, innerPtrs...)\n")
			g.printf("\t}\n")
		}
	}
	g.printf("\treturn n, ptrs\n}\n\n")
}

func (g *generator) generateCreatePgColumns(s structInfo) {
	g.printf("func (e %s) CreatePgColumns() []string {\n", s.Name)
	g.printf("\tcols := []string{\n")
	for _, f := range s.Fields {
		if f.IsDelegate {
			continue
		}
		pgInfo := f.Impls["pgimpl"]
		if pgInfo.Create {
			g.printf("\t\t\"%s\",\n", pgInfo.ColumnName)
		}
	}
	g.printf("\t}\n")
	for _, f := range s.Fields {
		if f.IsDelegate {
			g.printf("\tfor _, c := range e.%s.CreatePgColumns() {\n", f.Name)
			g.printf("\t\tcols = append(cols, \"%s\" + c)\n", f.Prefix)
			g.printf("\t}\n")
		}
	}
	g.printf("\treturn cols\n}\n\n")
}

func (g *generator) generateCreatePgColumnVals(s structInfo) {
	g.printf("func (e %s) CreatePgColumnVals() []any {\n", s.Name)
	g.printf("\tvals := []any{\n")
	for _, f := range s.Fields {
		if f.IsDelegate {
			continue
		}
		pgInfo := f.Impls["pgimpl"]
		if pgInfo.Create {
			g.printf("\t\te.%s,\n", f.Name)
		}
	}
	g.printf("\t}\n")
	for _, f := range s.Fields {
		if f.IsDelegate {
			g.printf("\tvals = append(vals, e.%s.CreatePgColumnVals()...)\n", f.Name)
		}
	}
	g.printf("\treturn vals\n}\n\n")
}

func (g *generator) generateIdentifyPgColumns(s structInfo) {
	g.printf("func (e %s) IdentifyPgColumns() []string {\n", s.Name)
	g.printf("\tcols := []string{\n")
	for _, f := range s.Fields {
		if f.IsDelegate {
			continue
		}
		pgInfo := f.Impls["pgimpl"]
		if pgInfo.Identify {
			g.printf("\t\t\"%s\",\n", pgInfo.ColumnName)
		}
	}
	g.printf("\t}\n")
	for _, f := range s.Fields {
		if f.IsDelegate {
			g.printf("\tfor _, c := range e.%s.IdentifyPgColumns() {\n", f.Name)
			g.printf("\t\tcols = append(cols, \"%s\" + c)\n", f.Prefix)
			g.printf("\t}\n")
		}
	}
	g.printf("\treturn cols\n}\n\n")
}

func (g *generator) generateIdentifyPgColumnVals(s structInfo) {
	g.printf("func (e %s) IdentifyPgColumnVals() []any {\n", s.Name)
	g.printf("\tvals := []any{\n")
	for _, f := range s.Fields {
		if f.IsDelegate {
			continue
		}
		pgInfo := f.Impls["pgimpl"]
		if pgInfo.Identify {
			g.printf("\t\te.%s,\n", f.Name)
		}
	}
	g.printf("\t}\n")
	for _, f := range s.Fields {
		if f.IsDelegate {
			g.printf("\tvals = append(vals, e.%s.IdentifyPgColumnVals()...)\n", f.Name)
		}
	}
	g.printf("\treturn vals\n}\n\n")
}

func (g *generator) generateUpdatePgColumns(s structInfo) {
	g.printf("func (e %s) UpdatePgColumns() []string {\n", s.Name)
	g.printf("\tcols := []string{\n")
	for _, f := range s.Fields {
		if f.IsDelegate {
			continue
		}
		pgInfo := f.Impls["pgimpl"]
		if pgInfo.Update {
			g.printf("\t\t\"%s\",\n", pgInfo.ColumnName)
		}
	}
	g.printf("\t}\n")
	for _, f := range s.Fields {
		if f.IsDelegate {
			g.printf("\tfor _, c := range e.%s.UpdatePgColumns() {\n", f.Name)
			g.printf("\t\tcols = append(cols, \"%s\" + c)\n", f.Prefix)
			g.printf("\t}\n")
		}
	}
	g.printf("\treturn cols\n}\n\n")
}

func (g *generator) generateUpdatePgColumnVals(s structInfo) {
	g.printf("func (e %s) UpdatePgColumnVals() []any {\n", s.Name)
	g.printf("\tvals := []any{\n")
	for _, f := range s.Fields {
		if f.IsDelegate {
			continue
		}
		pgInfo := f.Impls["pgimpl"]
		if pgInfo.Update {
			g.printf("\t\te.%s,\n", f.Name)
		}
	}
	g.printf("\t}\n")
	for _, f := range s.Fields {
		if f.IsDelegate {
			g.printf("\tvals = append(vals, e.%s.UpdatePgColumnVals()...)\n", f.Name)
		}
	}
	g.printf("\treturn vals\n}\n\n")
}
