// Code generated by gimpl. DO NOT EDIT.
package orders

import (
	shared "github.com/pedramktb/go-gimpl/example/shared"
	"strings"
)

func (e Order) SortPtr(field string) any {
	switch field {
	default:
		if strings.HasPrefix(field, "dest_") {
			return e.Destination.SortPtr(strings.TrimPrefix(field, "dest_"))
		}
	}
	return nil
}

func (e Order) FilterPtr(field string) any {
	switch field {
	default:
		if strings.HasPrefix(field, "dest_") {
			return e.Destination.FilterPtr(strings.TrimPrefix(field, "dest_"))
		}
	}
	return nil
}

func (e Order) PgColumn(field string) string {
	switch field {
	case "id":
		return "id"
	default:
		if strings.HasPrefix(field, "dest_") {
			return "dest_" + e.Destination.PgColumn(strings.TrimPrefix(field, "dest_"))
		}
	}
	return ""
}

func (e Order) PgColumns() []string {
	cols := []string{
		"id",
	}
	for _, c := range e.Destination.PgColumns() {
		cols = append(cols, "dest_"+c)
	}
	return cols
}

func (e Order) NewWithPgColumnPtrs() (any, []any) {
	n := &Order{}
	ptrs := []any{
		&n.ID,
	}
	{
		inner, innerPtrs := n.Destination.NewWithPgColumnPtrs()
		if val, ok := inner.(*shared.Geo); ok {
			n.Destination = *val
		}
		ptrs = append(ptrs, innerPtrs...)
	}
	return n, ptrs
}

func (e Order) CreatePgColumns() []string {
	cols := []string{}
	for _, c := range e.Destination.CreatePgColumns() {
		cols = append(cols, "dest_"+c)
	}
	return cols
}

func (e Order) CreatePgColumnVals() []any {
	vals := []any{}
	vals = append(vals, e.Destination.CreatePgColumnVals()...)
	return vals
}
